const COVERIMAGES = [
  {
    id: "1",
    folder: "mytheresa",
    path: "/images/cover/1.jpg",
    title: "My Theresa Lookbook",
    noOfItems: 10,
    filter: "lookbook",
  },
  {
    id: "2",
    folder: "holzweiler-ecomm",
    path: "/images/cover/2.jpg",
    title: "Holzweiler E-commerce",
    noOfItems: 12,
    filter: "ecommerce",
  },
  {
    id: "3",
    folder: "one-magazine",
    path: "/images/cover/3.jpg",
    title: "One Magazine",
    noOfItems: 9,
    filter: "editorial",
  },
  {
    id: "4",
    folder: "icon-april-21",
    path: "/images/cover/4.jpg",
    title: "Icon Magazine",
    noOfItems: 1,
    filter: "editorial",
  },
  {
    id: "5",
    folder: "sabrina-goh",
    path: "/images/cover/5.jpg",
    title: "Sabrina Goh E-commerce",
    noOfItems: 13,
    filter: "ecommerce",
  },
  {
    id: "6",
    folder: "pin-prestige-nov-21",
    path: "/images/cover/6.jpg",
    title: "PIN Prestige Magazine Nov 2021 Issue",
    noOfItems: 2,
    filter: "editorial",
  },
  {
    id: "7",
    folder: "icon-june-21",
    path: "/images/cover/7.jpg",
    title: "Icon Magazine June 2021 Issue",
    noOfItems: 5,
    filter: "editorial",
  },
  {
    id: "8",
    folder: "jw-anderson",
    path: "/images/cover/8.jpg",
    title: "J.W Anderson F/W London Fashion Week",
    noOfItems: 2,
    filter: "runway",
  },
  {
    id: "9",
    folder: "nuyou-mar-21",
    path: "/images/cover/9.jpg",
    title: "NUYOU Magazine March 2021 Issue",
    noOfItems: 4,
    filter: "editorial",
  },
  {
    id: "10",
    folder: "pin-prestige-may-21",
    path: "/images/cover/10.jpg",
    title: "PIN Prestige May 2021 Issue",
    noOfItems: 8,
    filter: "editorial",
  },
  {
    id: "11",
    folder: "phylum-of-beauty",
    path: "/images/cover/11.jpg",
    title: "Phylum of Beauty",
    noOfItems: 6,
    filter: "editorial",
  },
  {
    id: "12",
    folder: "holzweiler-lookbook",
    path: "/images/cover/12.jpg",
    title: "Holzweiler Lookbook",
    noOfItems: 19,
    filter: "lookbook",
  },
  {
    id: "13",
    folder: "odalisque",
    path: "/images/cover/13.jpg",
    title: "Odalisque Magazine",
    noOfItems: 16,
    filter: "editorial",
  },
  {
    id: "14",
    folder: "nuyou-beauty",
    path: "/images/cover/14.jpg",
    title: "NUYOU Magazine Beauty",
    noOfItems: 4,
    filter: "editorial",
  },
  {
    id: "15",
    folder: "the-peak",
    path: "/images/cover/15.jpg",
    title: "The Peak Magazine",
    noOfItems: 5,
    filter: "editorial",
  },
  {
    id: "16",
    folder: "icon-mar-2021",
    path: "/images/cover/16.jpg",
    title: "Icon Magazine",
    noOfItems: 5,
    filter: "editorial",
  },
  {
    id: "17",
    folder: "eileen",
    path: "/images/cover/17.jpg",
    title: "LASALLE Graduation Project",
    noOfItems: 21,
    filter: "lookbook",
  },
];

const DIGITALS = [
  {
    id: "1",
    path: "/images/digitals/1.jpg",
  },
  {
    id: "2",
    path: "/images/digitals/2.jpg",
  },
  {
    id: "3",
    path: "/images/digitals/3.jpg",
  },
  {
    id: "4",
    path: "/images/digitals/4.jpg",
  },
  {
    id: "5",
    path: "/images/digitals/5.jpg",
  },
  {
    id: "6",
    path: "/images/digitals/6.jpg",
  },
  {
    id: "7",
    path: "/images/digitals/7.jpg",
  },
  {
    id: "8",
    path: "/images/digitals/8.jpg",
  },
  {
    id: "9",
    path: "/images/digitals/9.jpg",
  },
  {
    id: "10",
    path: "/images/digitals/10.jpg",
  },
  {
    id: "11",
    path: "/images/digitals/11.jpg",
  },
  {
    id: "12",
    path: "/images/digitals/12.jpg",
  },
];

const SKILLS = {
  pytorch: "/images/pytorch.png",
  react: "/images/react.png",
  angular: "/images/angular.png",
  html: "/images/html.png",
  css: "/images/css.png",
  java: "/images/java.png",
  javascript: "/images/javascript.png",
  cplus: "/images/c++.png",
  typescript: "/images/typescript.png",
  spring: "/images/spring.png",
  python: "/images/python.png",
  sql: "/images/sql.png",
  numpy: "/images/numpy.png",
  pandas: "/images/pandas.png",
  scikitlearn: "/images/scikitlearn.png",
};

export { COVERIMAGES, DIGITALS, SKILLS };
